{
    "openapi": "3.0.0",
    "info": {
        "title": "News aggregator API documentation",
        "version": "1.0"
    },
    "paths": {
        "/api/v1/articles": {
            "get": {
                "summary": "articles resource",
                "operationId": "daffc9d151a0c7c956d1157d38e78859",
                "parameters": [
                    {
                        "name": "date",
                        "in": "query",
                        "description": "The date of the article",
                        "required": false,
                        "schema": {
                            "type": "date"
                        }
                    },
                    {
                        "name": "category",
                        "in": "query",
                        "description": "The category of the article",
                        "required": false,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "source",
                        "in": "query",
                        "description": "The source of the article",
                        "required": false,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "perPage",
                        "in": "query",
                        "description": "number of articles per page",
                        "required": false,
                        "schema": {
                            "type": "number"
                        }
                    },
                    {
                        "name": "page",
                        "in": "query",
                        "description": "page number",
                        "required": false,
                        "schema": {
                            "type": "number"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "examples": {
                                    "result": {
                                        "summary": "An result object.",
                                        "value": {
                                            "data": {
                                                "slug": "article1",
                                                "title": "article1",
                                                "description": "Laborum nesciunt ..",
                                                "content": "etur minus architect ..",
                                                "author": "r King",
                                                "category": "science",
                                                "source": "Newscred",
                                                "published_at": "2020-01-01"
                                            },
                                            "links": {
                                                "first": "articles?page=1",
                                                "next": "articles?page=2"
                                            },
                                            "meta": {
                                                "current_page": 1,
                                                "from": 1,
                                                "path": "/articles",
                                                "per_page": 10,
                                                "to": 10
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "unauthenticated",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "examples": {
                                    "result": {
                                        "summary": "An result object.",
                                        "value": {
                                            "message": "unauthenticated."
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/login": {
            "post": {
                "summary": "user login",
                "operationId": "05d536c846963ff3d47fe782fa7f5435",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {
                                    "email": {
                                        "type": "email"
                                    },
                                    "password": {
                                        "type": "password"
                                    }
                                },
                                "type": "object",
                                "example": {
                                    "email": "john@doe.com",
                                    "password": "re412##AB"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Login success",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "examples": {
                                    "result": {
                                        "summary": "An result object.",
                                        "value": {
                                            "data": {
                                                "user": {
                                                    "name": "john doe",
                                                    "email": "john@doe.com"
                                                },
                                                "token": "Rnw5mhtGF7e"
                                            },
                                            "message": "You have logged in successfully."
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "failed login",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "examples": {
                                    "result": {
                                        "summary": "An result object.",
                                        "value": {
                                            "message": "The provided credentials don't match our records."
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/logout": {
            "post": {
                "summary": "user logout",
                "operationId": "90c6c29d208bd685486aca10d32d3dd4",
                "responses": {
                    "200": {
                        "description": "Logout success",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "examples": {
                                    "result": {
                                        "summary": "An result object.",
                                        "value": {
                                            "message": "You have logged out successfully."
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/forgot-password": {
            "post": {
                "summary": "user reset password",
                "operationId": "e9dea57b981b47ff86a3786308ed9036",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {
                                    "email": {
                                        "type": "email"
                                    }
                                },
                                "type": "object",
                                "example": {
                                    "email": "john@doe.com"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Link sent successfully",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "examples": {
                                    "result": {
                                        "summary": "An result object.",
                                        "value": {
                                            "data": [],
                                            "message": "A reset link has been sent to your email."
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "429": {
                        "description": "Too many attempts",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "examples": {
                                    "result": {
                                        "summary": "An result object.",
                                        "value": {
                                            "message": "Too Many Attempts."
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/reset-password": {
            "post": {
                "summary": "user reset password",
                "operationId": "543c68a861604eb76de1e4934ec9884f",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {
                                    "email": {
                                        "type": "email"
                                    },
                                    "token": {
                                        "type": "email"
                                    },
                                    "password": {
                                        "type": "email"
                                    }
                                },
                                "type": "object",
                                "example": {
                                    "email": "john@doe.com",
                                    "token": "ki8191kaa",
                                    "password": "Pww123##pp"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Password updated successfully",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "examples": {
                                    "result": {
                                        "summary": "An result object.",
                                        "value": {
                                            "data": [],
                                            "message": "Your password has been updated successfully."
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "examples": {
                                    "result-1": {
                                        "summary": "invalid token",
                                        "value": {
                                            "success": false,
                                            "data": null,
                                            "errors": {
                                                "token": [
                                                    "Reset link is invalid or has expired."
                                                ]
                                            }
                                        }
                                    },
                                    "result-2": {
                                        "summary": "invalid email",
                                        "value": {
                                            "success": false,
                                            "data": null,
                                            "errors": {
                                                "email": [
                                                    "Invalid email."
                                                ]
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/register": {
            "post": {
                "summary": "user registration",
                "operationId": "ef1fc55fd1293ef6d3c0a18421f914ee",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {
                                    "name": {
                                        "type": "string"
                                    },
                                    "email": {
                                        "type": "email"
                                    },
                                    "password": {
                                        "type": "password"
                                    },
                                    "password_confirmation": {
                                        "type": "password"
                                    }
                                },
                                "type": "object",
                                "example": {
                                    "name": "john doe",
                                    "email": "john@doe.com",
                                    "password": "re412##AB",
                                    "password_confirmation": "re412##AB"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Registration success",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "examples": {
                                    "result": {
                                        "summary": "An result object.",
                                        "value": {
                                            "data": {
                                                "user": {
                                                    "name": "john doe",
                                                    "email": "john@doe.com"
                                                },
                                                "token": "Rnw5mhtGF7e"
                                            },
                                            "message": "Registered successfully."
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "examples": {
                                    "result": {
                                        "summary": "An result object.",
                                        "value": {
                                            "success": false,
                                            "data": null,
                                            "errors": {
                                                "email": [
                                                    "The email field must be a valid email address."
                                                ]
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "components": {
        "securitySchemes": {
            "sanctum": {
                "type": "apiKey",
                "description": "Enter token in format (Bearer <token>)",
                "name": "Authorization",
                "in": "header"
            }
        }
    }
}